### ISSUE TITLE
Getting error with devise_mailjet

### ISSUE THREAD

**Issue by bhavyabh** [zedalaye/devise_mailjet#5]
Hello!
We are using this gem to enable users to join our mailing list when they create an account. We have done all the set up mentioned in the document. Got the following error. 
  
Do you happen to know what we are doing incorrectly? Thank you!

![mailjet](https://user-images.githubusercontent.com/34382500/56151036-4fbfd200-5f7e-11e9-8f7b-a3a1f28b131a.PNG)

**Comment by zedalaye** [comment]
Don't know if you still have to use this gem but... I may have fixed the problem...
